Wednesday, 10 April 2013 
============================================================

I'm not really sure how to handle errors...

I can abort, with something like this:  

    if (!$item)
        App::abort(404, 'Item ' . $params . ' was not found');

    {"errors":["Page http:\/\/api.shop\/items\/99 was not found."]}
    {"errors":["Item 99 was not found"]}
      
or I can return a value, with something like this:

    if (!$item)
        return $this->notFound("Item " . $params . ' was not found');

    {"errors":["Item 99 was not found"]}

Let's say, for argument's sake, right now, that best practice is to throw an exception.

Testing for that is a bit tricky....

I've created a mock of an exception, which works fine except that it doesn't return a value when the getMessage function is called...

I think that we should either return a json response, or an error message. Nothing in between. 

Let's see if this works:

    App::abort(400, $validator->errors()->all(':message'));      

It doesn't...
This does, though:

    App::abort(400, $validator->errors()->toJson());


Thursday, 11 April 2013 
============================================================

This sends a json string to my error handler:

    App::abort(400, $validator->errors()->toJson());

To handle it in the error handler, I need to do this:

    // If we were passed a json string, rebuild it
    $data = json_decode($exception->getMessage());
    if (!$data) {
        $json = array('errors' => array($exception->getMessage()));
    } else {
        $json = array('errors' => $data);
    }
    return Response::json($json)->setStatusCode($exception->getStatusCode());


I finally found out how to mock core classes (eg, validator):

    http://forums.laravel.io/viewtopic.php?id=5779

    public function testFailToStoreItemDueToValidationError()
    {
        $validator = Mockery::mock('Illuminate\Validation\Factory');
        $validator->shouldReceive('make')->once()->andReturn($validator)
            ->shouldReceive('passes')->once()->andReturn(False)
            ->shouldReceive('errors->toJson')->once()->andReturn(JSON_ERROR);
        Validator::swap($validator);
        $json = '{"name":"n","details":"d"}';
        $this->postUriWithException('items', $json, 400, 'error'); 
    }

I just realized that, with phpunit, I ultimately really just want a couple of test cases -- stuff I'm working on now, and everything. So, for the stuff I'm working on right now, I can tag it with:

    /**
     * @group now
     */
    
Then, I can run phpunit with this flag:

    phpunit --group now

For everything, just run phpunit.
    